### PR TITLE
feat: syntax highlighting for README.md

### PR DESCRIPTION
**Pull request by Charlotteis**
I was also going to add some emoji in, but I thought syntax highlighting may be more likely to be accepted.

It's been a while since we've sat down together in the gitosphere.

🌺

### CODE REVIEW

**Comment by norm** [comment]
I'll merge it if you fix it so it doesn't remove the blank lines I like so much. 😘

**Comment by norm** [comment]
(hint, open the diff page and add `?w=1` to the URL)

**Comment by norm** [comment]
I did it myself whilst cheekily rewriting history.

**Comment by Charlotteis** [comment]
Sorry norm! Busy week.

**Pull request closed without merging**
